email_settings:
  sender_email: 
  sender_password:
  receiver_email: 
  smtp_server: 
  smtp_port: 587

git_settings:
  repo_path: /Users/nihalsingh/Desktop/Learning/04. Social Chatter Summary
  remote_name: origin
  branch_name: main

scraper_settings:
  keywords:
    - Myanmar earthquake
    - Mandalay earthquake
    - Aftershock Myanmar
  twitter_username_list: []

daily_report_settings:
  output_folder: ./daily_reports/