email_settings:
  sender_email: your_email@gmail.com
  sender_password: your_app_password
  receiver_email: receiver_email@gmail.com
  smtp_server: smtp.gmail.com
  smtp_port: 587

git_settings:
  repo_path: /full/path/to/your/local/git/folder
  remote_name: origin
  branch_name: main

scraper_settings:
  keywords:
    - Myanmar earthquake
    - Mandalay earthquake
    - Aftershock Myanmar
  twitter_username_list: []

daily_report_settings:
  output_folder: ./daily_reports/